package exception;

public class exceptionDemo {
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("Inside Main method..!!");
		divis.divide();
	}
}
